server:

  port: 8086
  servlet:
    context-path: /file
spring:
  application:
    name: file-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/file-service?authSource=admin
cloudinary :
  cloudinary.cloud-name: "drunmvrkm"
  cloudinary.api-key: "116351667583516"
  cloudinary.api-secret: "fPlbFT-8F9YHCchd73rPo0-1udI"
